version: '3.6'
services:
    web:
        image: nginx:alpine
        container_name: warships-nginx
        networks:
            - warships_network
        ports:
            - 80:80
        volumes:
            - ./:/code:ro
            - .build/docker/nginx/conf/warships.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build:
            context: .build/docker/php81
        container_name: warships-php-fpm
        networks:
            - warships_network
        volumes:
            - ./:/code:cached
            - .build/docker/php81/php.ini:/usr/local/etc/php/conf.d/docker-warships.ini
        links:
            - mysql8
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM"
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_SESSION: "123"
    mysql8:
        image: mysql:8.0.28
        platform: linux/x86_64
        container_name: warships-mysql8
        networks:
            - warships_network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=warships-dev
        volumes:
            - .build/docker/mysql8/conf.d:/etc/mysql/conf.d
            - ./var/mysql8:/var/lib/mysql
        ports:
            - 3361:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: warships-phpmyadmin
        networks:
            - warships_network
        environment:
            - PMA_HOST=mysql8
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8085:80
        volumes:
            - /sessions
        links:
            - mysql8
networks:
    warships_network:
        driver: bridge
        name: warships_network
